### ISSUE TITLE
Ubuntu22.04+go1.22.3 install sepectre error

### ISSUE THREAD

**Issue by xiebangrong** [spectre-project/spectred#2]
go install . ./cmd/...
# github.com/spectre-project/go-muhash
../go/pkg/mod/github.com/spectre-project/go-muhash@v0.0.1/muhash.go:76:14: undefined: num3072
../go/pkg/mod/github.com/spectre-project/go-muhash@v0.0.1/muhash.go:77:14: undefined: num3072
../go/pkg/mod/github.com/spectre-project/go-muhash@v0.0.1/muhash.go:97:16: undefined: oneNum3072
../go/pkg/mod/github.com/spectre-project/go-muhash@v0.0.1/muhash.go:98:16: undefined: oneNum3072
../go/pkg/mod/github.com/spectre-project/go-muhash@v0.0.1/muhash.go:121:39: undefined: num3072
../go/pkg/mod/github.com/spectre-project/go-muhash@v0.0.1/muhash.go:133:42: undefined: num3072
../go/pkg/mod/github.com/spectre-project/go-muhash@v0.0.1/muhash.go:205:38: undefined: num3072
../go/pkg/mod/github.com/spectre-project/go-muhash@v0.0.1/muhash.go:223:75: undefined array length elementWordSize or missing type constraint
../go/pkg/mod/github.com/spectre-project/go-muhash@v0.0.1/muhash.go:223:91: undefined: word
../go/pkg/mod/github.com/spectre-project/go-muhash@v0.0.1/uint3072.go:9:12: undefined: elementWordSize
../go/pkg/mod/github.com/spectre-project/go-muhash@v0.0.1/muhash.go:98:16: too many errors
# github.com/spectre-project/spectred/cmd/spectrewallet/libspectrewallet/bip32
cmd/spectrewallet/libspectrewallet/bip32/extended_key.go:11:31: undefined: secp256k1.ECDSAPrivateKey
cmd/spectrewallet/libspectrewallet/bip32/extended_key.go:12:31: undefined: secp256k1.ECDSAPublicKey
cmd/spectrewallet/libspectrewallet/bip32/extended_key.go:21:52: undefined: secp256k1.ECDSAPrivateKey
cmd/spectrewallet/libspectrewallet/bip32/extended_key.go:26:52: undefined: secp256k1.ECDSAPublicKey
cmd/spectrewallet/libspectrewallet/bip32/child_key_derivation.go:22:31: undefined: secp256k1.DeserializeECDSAPrivateKeyFromSlice
cmd/spectrewallet/libspectrewallet/bip32/child_key_derivation.go:102:33: undefined: secp256k1.ECDSAPrivateKey
cmd/spectrewallet/libspectrewallet/bip32/child_key_derivation.go:145:32: undefined: secp256k1.ECDSAPublicKey
cmd/spectrewallet/libspectrewallet/bip32/serialization.go:69:38: undefined: secp256k1.DeserializeECDSAPrivateKeyFromSlice
cmd/spectrewallet/libspectrewallet/bip32/serialization.go:83:37: undefined: secp256k1.DeserializeECDSAPubKey

**Comment by 0xA001113** [comment]
C compiler is missing, muhash and secp256k1 are no native Golang libraries, they relies on underlying C code. Compile spectred with `CGO_ENABLED=1`. Please install C compiler like gcc and compile with `CGO_ENABLED=1 go install . ./cmd/...`
